### ISSUE TITLE
Can't use the bot anymore

### ISSUE THREAD

**Issue by hexandwhy** [sparkychild/FoxieBot#6]
I updated FoxieBot with the Main.js update that was created 7 days ago, and this happens.

"TypeError: path.resolve is not a function"

I've tried many things and it doesn't seem to be working so I guess I have to delete the new code and use the older version.

**Comment by sparkychild** [comment]
https://github.com/sparkychild/FoxieBot/commit/6ef563a8b2dfc5547e440cdf96aff7e0df64d605
fixed

**Comment by hexandwhy** [comment]
I realized that the "usage" command is outdated and still shows
http://www.smogon.com/stats/2016-01/ when
http://www.smogon.com/stats/2016-03/ is the most recent version. I couldn't
find where to edit it, so that didn't help.

Also, I made a custom command (named "dm") that I wanted to be unusable by
anybody but me, but I couldn't find a way to use "set" on all rooms at once.
Even if I added it in this list beneath, Mods and above seem to have been
able to use it. Is it possible to make it so only Admins can use it?

exports.lockedCommands = {
    "dm": true,
    "set": true,
    "autoban": true,
    "banword": true,
    "regexbanword": true,
    "settings": true,
    "setprivate": true,
